/*
 * Tomitribe Confidential
 *
 * Copyright Tomitribe Corporation. 2014
 *
 * The source code for this program is not published or otherwise divested 
 * of its trade secrets, irrespective of what has been deposited with the 
 * U.S. Copyright Office.
 */
package com.tomitribe.tribestream.registry.model.generator;

public class Descriptions {

    public static Iterable<String> random() {
        return Randoms.iterate(LIST);
    }

    public static final String[] LIST = {
            "Allows a registered application to revoke an issued OAuth 2 Bearer Token by presenting its client credentials. Once a Bearer Token has been invalidated, new creation",
            "The value of the bearer token to revoke.",
            "Allows a registered application to obtain an OAuth 2 Bearer Token, which can be used to make API requests on an application's own behalf, without a user",
            "Specifies the type of grant being requested by the application. At this time, only <tt>client_credentials</tt> is allowed.",
            "Returns a cursored collection of user IDs for every user following the specified user.",
            "The ID of the user for whom to return results for.",
            "The screen name of the user for whom to return results for.",
            "Causes the list of connections to be broken into pages of no more than 5000 IDs at a time. The number of IDs returned is not guaranteed to be 5000 as suspended",
            "Many programming environments will not consume our Tweet ids due to their size. Provide this option to have ids returned as strings instead",
            "Specifies the number of IDs attempt retrieval of, up to a maximum of 5,000 per distinct request. The value of <tt>count</tt> is best thought of as a",
            "Returns a cursored collection of user objects for users following the specified user.",
            "The ID of the user for whom to return results for.",
            "The screen name of the user for whom to return results for.",
            "Causes the results to be broken into pages. If no cursor is provided, a value of <tt>-1</tt> will be assumed, which is the first page.<br /><br",
            "The number of users to return per page, up to a maximum of 200. Defaults to 20.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "The user object <tt>entities</tt> node will be disincluded when set to <tt>false</tt>.",
            "Returns a collection of numeric IDs for every user who has a pending request to follow the authenticating user.",
            "Causes the list of connections to be broken into pages of no more than 5000 IDs at a time. The number of IDs returned is not guaranteed to be 5000 as suspended",
            "Many programming environments will not consume our Tweet ids due to their size. Provide this option to have ids returned as strings instead",
            "Returns the relationships of the authenticating user to the comma-separated list of up to 100 screen_names or user_ids provided. Values for connections can be:",
            "A comma separated list of screen names, up to 100 are allowed in a single request.",
            "A comma separated list of user IDs, up to 100 are allowed in a single request.",
            "Returns a collection of user_ids that the currently authenticated user does not want to receive retweets from. Use POST friendships/update to set the &amp;quot;no",
            "Many programming environments will not consume our ids due to their size. Provide this option to have ids returned as strings instead. Read more about <a",
            "Returns a collection of numeric IDs for every protected user for whom the authenticating user has a pending follow request.",
            "Causes the list of connections to be broken into pages of no more than 5000 IDs at a time. The number of IDs returned is not guaranteed to be 5000 as suspended",
            "Many programming environments will not consume our Tweet ids due to their size. Provide this option to have ids returned as strings instead",
            "Returns detailed information about the relationship between two arbitrary users.",
            "The user_id of the subject user.",
            "The screen_name of the subject user.",
            "The user_id of the target user.",
            "The screen_name of the target user.",
            "Allows the authenticating users to follow the user specified in the ID parameter. Returns the befriended user in the requested format when successful. Returns a",
            "The screen name of the user for whom to befriend.",
            "The ID of the user for whom to befriend.",
            "Enable notifications for the target user.",
            "Allows the authenticating user to unfollow the user specified in the ID parameter. Returns the unfollowed user in the requested format when successful. Returns a",
            "The screen name of the user for whom to unfollow.",
            "The ID of the user for whom to unfollow.",
            "Allows one to enable or disable retweets and device notifications from the specified user.",
            "The screen name of the user for whom to befriend.",
            "The ID of the user for whom to befriend.",
            "Enable/disable device notifications from the target user.",
            "Enable/disable retweets from the target user.",
            "This endpoint requires special permission to access. Returns all public statuses. Few applications require this level of access. Creative use of a combination of",
            "The number of messages to backfill. See <a href=https://dev.twitter.com/docs/streaming-apis/parameters#count>the count parameter documentation</a>",
            "Specifies whether messages should be length-delimited. See <a href=https://dev.twitter.com/docs/streaming-apis/parameters#delimited>the delimited",
            "Specifies whether stall warnings should be delivered. See <a href=https://dev.twitter.com/docs/streaming-apis/parameters#stall_warnings>the",
            "Returns a collection of the most recent Tweets and retweets posted by the authenticating user and the users they follow. The home timeline is central to how most",
            "Specifies the number of records to retrieve. Must be less than or equal to 200. Defaults to 20.",
            "Returns results with an ID greater than (that is, more recent than) the specified ID. There are limits to the number of Tweets which can be accessed through the",
            "Returns results with an ID less than (that is, older than) or equal to the specified ID.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet returned in a timeline will include a user object",
            "This parameter will prevent replies from appearing in the returned timeline. Using <tt>exclude_replies</tt> with the <tt>count</tt>",
            "This parameter enhances the contributors element of the status response to include the screen_name of the contributor. By default only the user_id of the",
            "The <tt>entities</tt> node will be disincluded when set to <tt>false</tt>.",
            "Returns the 20 most recent mentions (tweets containing a users's @screen_name) for the authenticating user. The timeline returned is the equivalent of the",
            "Specifies the number of tweets to try and retrieve, up to a maximum of 200. The value of <tt>count</tt> is best thought of as a limit to the number",
            "Returns results with an ID greater than (that is, more recent than) the specified ID. There are limits to the number of Tweets which can be accessed through the",
            "Returns results with an ID less than (that is, older than) or equal to the specified ID.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet returned in a timeline will include a user object",
            "This parameter enhances the contributors element of the status response to include the screen_name of the contributor. By default only the user_id of the",
            "The <tt>entities</tt> node will be disincluded when set to <tt>false</tt>.",
            "Returns information allowing the creation of an embedded representation of a Tweet on third party sites. See the oEmbed specification for information about the",
            "The Tweet/status ID to return embed code for.",
            "The URL of the Tweet/status to be embedded.",
            "The maximum width in pixels that the embed should be rendered at. This value is constrained to be between <strong>250</strong> and <strong>550</strong>",
            "Specifies whether the embedded Tweet should automatically expand images which were uploaded via <a",
            "Specifies whether the embedded Tweet should automatically show the original message in the case that the embedded Tweet is a reply. When set to either <tt>true</tt>,",
            "Specifies whether the embedded Tweet HTML should include a &amp;lt;script&amp;gt; element pointing to <tt>widgets.js</tt>. In cases where a page",
            "Specifies whether the embedded Tweet should be left aligned, right aligned, or centered in the page. Valid values are <tt>left</tt>, <tt>right</tt>,",
            "A value for the TWT <tt>related</tt> parameter, as described in <a href=https://dev.twitter.com/docs/intents>Web Intents</a>. This",
            "Language code for the rendered embed. This will affect the text and localization of the rendered HTML.",
            "Returns a collection of up to 100 user IDs belonging to users who have retweeted the tweet specified by the id parameter. This method offers similar data to GET",
            "The numerical ID of the desired status.",
            "Causes the list of IDs to be broken into pages of no more than 100 IDs at a time. The number of IDs returned is not guaranteed to be 100 as suspended users are",
            "Many programming environments will not consume our ids due to their size. Provide this option to have ids returned as strings instead. Read more about <a",
            "Returns a collection of the 100 most recent retweets of the tweet specified by the id parameter.",
            "The numerical ID of the desired status.",
            "Specifies the number of records to retrieve. Must be less than or equal to 100.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet returned in a timeline will include a user object",
            "Returns the most recent tweets authored by the authenticating user that have been retweeted by others. This timeline is a subset of the user's GET",
            "Specifies the number of records to retrieve. Must be less than or equal to 100. If omitted, 20 will be assumed.",
            "Returns results with an ID greater than (that is, more recent than) the specified ID. There are limits to the number of Tweets which can be accessed through the",
            "Returns results with an ID less than (that is, older than) or equal to the specified ID.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet returned in a timeline will include a user object",
            "The tweet <tt>entities</tt> node will be disincluded when set to <tt>false</tt>.",
            "The user <tt>entities</tt> node will be disincluded when set to <tt>false</tt>.",
            "Returns a small random sample of all public statuses. The Tweets returned by the default access level are the same, so if two different clients connect to this",
            "Specifies whether messages should be length-delimited. See <a href=https://dev.twitter.com/docs/streaming-apis/parameters#delimited>the delimited",
            "Specifies whether stall warnings should be delivered. See <a href=https://dev.twitter.com/docs/streaming-apis/parameters#stall_warnings>the",
            "Returns a single Tweet, specified by the id parameter. The Tweet's author will also be embedded within the tweet. See Embeddable Timelines, Embeddable",
            "The numerical ID of the desired Tweet.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet returned in a timeline will include a user object",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, any Tweets returned that have been retweeted by the",
            "The <tt>entities</tt> node will be disincluded when set to <tt>false</tt>.",
            "Returns a collection of the most recent Tweets posted by the user indicated by the screen_name or user_id parameters.",
            "The ID of the user for whom to return results for.",
            "The screen name of the user for whom to return results for.",
            "Returns results with an ID greater than (that is, more recent than) the specified ID. There are limits to the number of Tweets which can be accessed through the",
            "Specifies the number of tweets to try and retrieve, up to a maximum of 200 per distinct request. The value of <tt>count</tt> is best thought of as a",
            "Returns results with an ID less than (that is, older than) or equal to the specified ID.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet returned in a timeline will include a user object",
            "This parameter will prevent replies from appearing in the returned timeline. Using <tt>exclude_replies</tt> with the <tt>count</tt>",
            "This parameter enhances the contributors element of the status response to include the screen_name of the contributor. By default only the user_id of the",
            "When set to <tt>false</tt>, the timeline will strip any native retweets (though they will still count toward both the maximal length of the timeline",
            "Destroys the status specified by the required ID parameter. The authenticating user must be the author of the specified status. Returns the destroyed status if",
            "The numerical ID of the desired status.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet returned in a timeline will include a user object",
            "Returns public statuses that match one or more filter predicates. Multiple parameters may be specified which allows most clients to use a single connection to the",
            "A comma separated list of user IDs, indicating the users to return statuses for in the stream.",
            "Keywords to track. Phrases of keywords are specified by a comma-separated list. See <a href=https://dev.twitter.com/docs/streaming-apis/parameters#track>the",
            "Specifies a set of bounding boxes to track. See <a href=https://dev.twitter.com/docs/streaming-apis/parameters#locations>the locations parameter",
            "Specifies whether messages should be length-delimited. See <a href=https://dev.twitter.com/docs/streaming-apis/parameters#delimited>the delimited",
            "Specifies whether stall warnings should be delivered. See <a href=https://dev.twitter.com/docs/streaming-apis/parameters#stall_warnings>the",
            "Retweets a tweet. Returns the original tweet with retweet details embedded.",
            "The numerical ID of the desired status.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet returned in a timeline will include a user object",
            "Updates the authenticating user's current status, also known as tweeting. To upload an image to accompany the tweet, use POST statuses/update_with_media.",
            "The text of your status update, typically up to 140 characters. URL encode as necessary. <a href=https://dev.twitter.com/docs/tco-link-wrapper/faq>t.co",
            "The ID of an existing status that the update is in reply to.",
            "The latitude of the location this tweet refers to. This parameter will be ignored unless it is inside the range -90.0 to +90.0 (North is positive) inclusive. It",
            "The longitude of the location this tweet refers to. The valid ranges for longitude is -180.0 to +180.0 (East is positive) inclusive. This parameter will be",
            "A place in the world. These IDs can be retrieved from <a href=https://dev.twitter.com/docs/api/1/get/geo/reverse_geocode>GET geo/reverse_geocode</a>.",
            "Whether or not to put a pin on the exact coordinates a tweet has been sent from.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet returned in a timeline will include a user object",
            "Updates the authenticating user's current status and attaches media for upload. In other words, it creates a Tweet with a picture attached. Unlike POST",
            "The text of your status update. URL encode as necessary. <a href=https://dev.twitter.com/docs/tco-link-wrapper/faq>t.co link wrapping</a> may",
            "Up to <tt>max_media_per_upload</tt> files may be specified in the request, each named <tt>media[]</tt>. Supported image formats are PNG,",
            "Set to <tt>true</tt> for content which may not be suitable for every audience.",
            "The ID of an existing status that the update is in reply to.",
            "The latitude of the location this tweet refers to. This parameter will be ignored unless it is inside the range -90.0 to +90.0 (North is positive) inclusive. It",
            "The longitude of the location this tweet refers to. The valid ranges for longitude is -180.0 to +180.0 (East is positive) inclusive. This parameter will be",
            "A place in the world identified by a Twitter place ID. Place IDs can be retrieved from geo/reverse_geocode.",
            "Whether or not to put a pin on the exact coordinates a tweet has been sent from.",
            "Returns the locations that Twitter has trending topic information for. The response is an array of &amp;quot;locations&amp;quot; that encode the location's",
            "Returns the locations that Twitter has trending topic information for, closest to a specified location. The response is an array of &amp;quot;locations&amp;quot;",
            "If provided with a <tt>long</tt> parameter the available trend locations will be sorted by distance, nearest to furthest, to the co-ordinate pair.",
            "If provided with a <tt>lat</tt> parameter the available trend locations will be sorted by distance, nearest to furthest, to the co-ordinate pair. The",
            "Returns the top 10 trending topics for a specific WOEID, if trending information is available for it. The response is an array of &amp;quot;trend&amp;quot; objects",
            "The <a href=http://developer.yahoo.com/geo/geoplanet/ rel=external>Yahoo! Where On Earth ID</a> of the location to return trending information",
            "Setting this equal to <tt>hashtags</tt> will remove all hashtags from the trends list.",
            "Returns the authenticated user's saved search queries.",
            "Retrieve the information for the saved search represented by the given id. The authenticating user must be the owner of saved search ID being requested.",
            "The ID of the saved search.",
            "Create a new saved search for the authenticated user. A user may only have 25 saved searches.",
            "The query of the search the user would like to save.",
            "Destroys a saved search for the authenticating user. The authenticating user must be the owner of saved search id being destroyed.",
            "The ID of the saved search.",
            "Allows a Consumer application to use an OAuth request_token to request user authorization. This method is a replacement of Section 6.2 of the OAuth 1.0",
            "Forces the user to enter their credentials to ensure the correct users account is authorized.",
            "Prefills the username input box of the OAuth login screen with the given value.",
            "Allows a Consumer application to use an OAuth Request Token to request user authorization. This method fulfills Section 6.2 of the OAuth 1.0 authentication flow.",
            "Forces the user to enter their credentials to ensure the correct users account is authorized.",
            "Prefills the username input box of the OAuth login screen with the given value.",
            "Allows a Consumer application to exchange the OAuth Request Token for an OAuth Access Token. This method fulfills Section 6.3 of the OAuth 1.0 authentication flow.",
            "The password of the user for which to obtain a token for. <strong>Required when using xAuth</strong>",
            "The username of the user to obtain a token for. <strong>Required when using xAuth</strong>",
            "Set this value to <tt>client_auth</tt>, without the quotes. <strong>Required when using xAuth</strong>",
            "If using the OAuth web-flow, set this parameter to the value of the <tt>oauth_verifier</tt> returned in the callback URL. If you are using",
            "Allows a Consumer application to obtain an OAuth Request Token to request user authorization. This method fulfills Section 6.1 of the OAuth 1.0 authentication flow.",
            "For OAuth 1.0a compliance this parameter is <strong>required</strong>. The value you specify here will be used as the URL a user is redirected to",
            "Overrides the access level an application requests to a users account. Supported values are <tt>read</tt> or <tt>write</tt>. This",
            "Returns relevant tweets that match a specified query.",
            "A UTF-8, URL-encoded search query of 1,000 characters maximum, including operators. Queries may additionally be limited by complexity.",
            "Returns tweets by users located within a given radius of the given latitude/longitude. The location is preferentially taking from the Geotagging API, but will",
            "Restricts tweets to the given language, given by an <a href=http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes>ISO 639-1</a> code. Language",
            "Specify the language of the query you are sending (only <tt>ja</tt> is currently effective). This is intended for language-specific consumers and the",
            "Optional. Specifies what type of search results you would prefer to receive. The current default is mixed. Valid values include:<br/>",
            "The number of tweets to return per page, up to a maximum of 100. Defaults to 15. This was formerly the rpp parameter in the old Search API.",
            "Returns tweets generated before the given date. Date should be formatted as YYYY-MM-DD. Keep in mind that the search index may not go back as far as the date you",
            "Returns results with an ID greater than (that is, more recent than) the specified ID. There are limits to the number of Tweets which can be accessed through the",
            "Returns results with an ID less than (that is, older than) or equal to the specified ID.",
            "The <tt>entities</tt> node will be disincluded when set to <tt>false</tt>.",
            "If supplied, the response will use the JSONP format with a callback of the given name. The usefulness of this parameter is somewhat diminished by the requirement",
            "Returns all the information about a known place.",
            "A place in the world. These IDs can be retrieved from geo/reverse_geocode.",
            "Given a latitude and a longitude, searches for up to 20 places that can be used as a place_id when updating a status. This request is an informative call and will",
            "The latitude to search around. This parameter will be ignored unless it is inside the range -90.0 to +90.0 (North is positive) inclusive. It will also be ignored",
            "The longitude to search around. The valid ranges for longitude is -180.0 to +180.0 (East is positive) inclusive. This parameter will be ignored if outside that",
            "A hint on the region in which to search. If a number, then this is a radius in meters, but it can also take a string that is suffixed with ft to specify feet.",
            "This is the minimal granularity of place types to return and must be one of: <tt>poi</tt>, <tt>neighborhood</tt>, <tt>city</tt>,",
            "A hint as to the number of results to return. This does not guarantee that the number of results returned will equal max_results, but instead informs how many",
            "If supplied, the response will use the JSONP format with a callback of the given name.",
            "Search for places that can be attached to a statuses/update. Given a latitude and a longitude pair, an IP address, or a name, this request will return a list of all",
            "The latitude to search around. This parameter will be ignored unless it is inside the range -90.0 to +90.0 (North is positive) inclusive. It will also be ignored",
            "The longitude to search around. The valid ranges for longitude is -180.0 to +180.0 (East is positive) inclusive. This parameter will be ignored if outside that",
            "Free-form text to match against while executing a geo-based query, best suited for finding nearby locations by name. Remember to URL encode the query.",
            "An IP address. Used when attempting to fix geolocation based off of the user's IP address.",
            "This is the minimal granularity of place types to return and must be one of: <tt>poi</tt>, <tt>neighborhood</tt>, <tt>city</tt>,",
            "A hint on the region in which to search. If a number, then this is a radius in meters, but it can also take a string that is suffixed with ft to specify feet.",
            "A hint as to the number of results to return. This does not guarantee that the number of results returned will equal max_results, but instead informs how many",
            "This is the <tt>place_id</tt> which you would like to restrict the search results to. Setting this value means only places within the given <tt>place_id</tt>",
            "This parameter searches for places which have this given street address. There are other well-known, and application specific attributes available. Custom",
            "If supplied, the response will use the JSONP format with a callback of the given name.",
            "Locates places near the given coordinates which are similar in name.",
            "The latitude to search around. This parameter will be ignored unless it is inside the range -90.0 to +90.0 (North is positive) inclusive. It will also be ignored",
            "The longitude to search around. The valid ranges for longitude is -180.0 to +180.0 (East is positive) inclusive. This parameter will be ignored if outside that",
            "The name a place is known as.",
            "This is the <tt>place_id</tt> which you would like to restrict the search results to. Setting this value means only places within the given <tt>place_id</tt>",
            "This parameter searches for places which have this given street address. There are other well-known, and application specific attributes available. Custom",
            "If supplied, the response will use the JSONP format with a callback of the given name.",
            "As of December 2nd, 2013, this endpoint is deprecated and retired and no longer functions. Place creation was used infrequently by third party applications and is",
            "The name a place is known as.",
            "The <tt>place_id</tt> within which the new place can be found. Try and be as close as possible with the containing place. For example, for a room in",
            "The token found in the response from geo/similar_places.",
            "The latitude the place is located at. This parameter will be ignored unless it is inside the range -90.0 to +90.0 (North is positive) inclusive. It will also be",
            "The longitude the place is located at. The valid ranges for longitude is -180.0 to +180.0 (East is positive) inclusive. This parameter will be ignored if outside",
            "This parameter searches for places which have this given street address. There are other well-known, and application specific attributes available. Custom",
            "If supplied, the response will use the JSONP format with a callback of the given name.",
            "Returns all lists the authenticating or specified user subscribes to, including their own. The user is specified using the user_id or screen_name parameters. If no",
            "The ID of the user for whom to return results for. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "The screen name of the user for whom to return results for. Helpful for disambiguating when a valid screen name is also a user ID.",
            "Set this to <tt>true</tt> if you would like owned lists to be returned first. See description above for information on how this parameter works.",
            "Returns the members of the specified list. Private list members will only be shown if the authenticated user owns the specified list.",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "Causes the collection of list members to be broken into pages of somewhat consistent size. If no cursor is provided, a value of <tt>-1</tt> will be",
            "The <tt>entities</tt> node will be disincluded when set to <tt>false</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Check if the specified user is a member of the specified list.",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "The ID of the user for whom to return results for. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "The screen name of the user for whom to return results for. Helpful for disambiguating when a valid screen name is also a user ID.",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet will include a node called entities. This node",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Add a member to a list. The authenticated user must own the list to be able to add members to it. Note that lists can't have more than 500 members.",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "The ID of the user for whom to return results for. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "The screen name of the user for whom to return results for. Helpful for disambiguating when a valid screen name is also a user ID.",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "Adds multiple members to a list, by specifying a comma-separated list of member ids or screen names. The authenticated user must own the list to be able to add",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "A comma separated list of user IDs, up to 100 are allowed in a single request.",
            "A comma separated list of screen names, up to 100 are allowed in a single request.",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "Removes the specified member from the list. The authenticated user must be the list's owner to remove members from the list.",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "The ID of the user to remove from the list. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "The screen name of the user for whom to remove from the list. Helpful for disambiguating when a valid screen name is also a user ID.",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "Removes multiple members from a list, by specifying a comma-separated list of member ids or screen names. The authenticated user must own the list to be able to",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "A comma separated list of user IDs, up to 100 are allowed in a single request.",
            "A comma separated list of screen names, up to 100 are allowed in a single request.",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "Returns the lists the specified user has been added to. If user_id or screen_name are not provided the memberships for the authenticating user are returned.",
            "The ID of the user for whom to return results for. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "The screen name of the user for whom to return results for. Helpful for disambiguating when a valid screen name is also a user ID.",
            "Breaks the results into pages. Provide a value of <tt>-1</tt> to begin paging. Provide values as returned in the response body's <tt>next_cursor</tt>",
            "When set to <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, will return just lists the authenticating user owns, and the user",
            "Returns the lists owned by the specified Twitter user. Private lists will only be shown if the authenticated user is also the owner of the lists.",
            "The ID of the user for whom to return results for.",
            "The screen name of the user for whom to return results for.",
            "The amount of results to return per page. Defaults to 20. No more than 1000 results will ever be returned in a single page.",
            "Breaks the results into pages. Provide a value of <tt>-1</tt> to begin paging. Provide values as returned in the response body's <tt>next_cursor</tt>",
            "Returns the specified list. Private lists will only be shown if the authenticated user owns the specified list.",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "Returns a timeline of tweets authored by members of the specified list. Retweets are included by default. Use the include_rts=false parameter to omit retweets.",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "Returns results with an ID greater than (that is, more recent than) the specified ID. There are limits to the number of Tweets which can be accessed through the",
            "Returns results with an ID less than (that is, older than) or equal to the specified ID.",
            "Specifies the number of results to retrieve per page.",
            "Entities are ON by default in API 1.1, each tweet includes a node called entities. This node offers a variety of metadata about the tweet in a discreet",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, the list timeline will contain native retweets (if they exist) in",
            "Returns the subscribers of the specified list. Private list subscribers will only be shown if the authenticated user owns the specified list.",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "Breaks the results into pages. A single page contains 20 lists. Provide a value of <tt>-1</tt> to begin paging. Provide values as returned in the",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet will include a node called entities. This node",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Check if the specified user is a subscriber of the specified list. Returns the user if they are subscriber.",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "The ID of the user for whom to return results for. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "The screen name of the user for whom to return results for. Helpful for disambiguating when a valid screen name is also a user ID.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet will include a node called entities. This node",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Subscribes the authenticated user to the specified list.",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "Unsubscribes the authenticated user from the specified list.",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "Obtain a collection of the lists the specified user is subscribed to, 20 lists per page by default. Does not include the user's own lists.",
            "The ID of the user for whom to return results for. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "The screen name of the user for whom to return results for. Helpful for disambiguating when a valid screen name is also a user ID.",
            "The amount of results to return per page. Defaults to 20. No more than 1000 results will ever be returned in a single page.",
            "Breaks the results into pages. Provide a value of <tt>-1</tt> to begin paging. Provide values as returned in the response body's <tt>next_cursor</tt>",
            "Creates a new list for the authenticated user. Note that you can't create more than 20 lists per account.",
            "The name for the list.",
            "Whether your list is public or private. Values can be <tt>public</tt> or <tt>private</tt>. If no mode is specified the list will be",
            "The description to give the list.",
            "Deletes the specified list. The authenticated user must own the list to be able to destroy it.",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "Updates the specified list. The authenticated user must own the list to be able to update it.",
            "The numerical <tt>id</tt> of the list.",
            "You can identify a list by its slug instead of its numerical id. If you decide to do so, note that you'll also have to specify the list owner using the <tt>owner_id</tt>",
            "The name for the list.",
            "Whether your list is public or private. Values can be <tt>public</tt> or <tt>private</tt>. If no mode is specified the list will be",
            "The description to give the list.",
            "The screen name of the user who owns the list being requested by a <tt>slug</tt>.",
            "The user ID of the user who owns the list being requested by a <tt>slug</tt>.",
            "Returns an array of numeric user ids the authenticating user is blocking. Important On October 15, 2012 this method will become cursored by default, altering the",
            "Many programming environments will not consume our ids due to their size. Provide this option to have ids returned as strings instead. Read more about <a",
            "Causes the list of IDs to be broken into pages of no more than 5000 IDs at a time. The number of IDs returned is not guaranteed to be 5000 as suspended users are",
            "Returns a collection of user objects that the authenticating user is blocking. Important On October 15, 2012 this method will become cursored by default, altering",
            "The <tt>entities</tt> node will not be included when set to <tt>false</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Causes the list of blocked users to be broken into pages of no more than 5000 IDs at a time. The number of IDs returned is not guaranteed to be 5000 as suspended",
            "Blocks the specified user from following the authenticating user. In addition the blocked user will not show in the authenticating users mentions or timeline (unless",
            "The screen name of the potentially blocked user. Helpful for disambiguating when a valid screen name is also a user ID.",
            "The ID of the potentially blocked user. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "The <tt>entities</tt> node will not be included when set to <tt>false</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Un-blocks the user specified in the ID parameter for the authenticating user. Returns the un-blocked user in the requested format when successful. If relationships",
            "The screen name of the potentially blocked user. Helpful for disambiguating when a valid screen name is also a user ID.",
            "The ID of the potentially blocked user. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "The <tt>entities</tt> node will not be included when set to <tt>false</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Returns the current configuration used by Twitter including twitter.com slugs which are not usernames, maximum photo resolutions, and t.co URL lengths. It is",
            "Returns the list of languages supported by Twitter along with their ISO 639-1 code. The ISO 639-1 code is the two letter value to use if you include lang with any of",
            "Returns Twitter's Privacy Policy.",
            "Returns the Twitter Terms of Service in the requested format. These are not the same as the Developer Rules of the Road.",
            "Returns a cursored collection of user IDs for every user the specified user is following (otherwise known as their &amp;quot;friends&amp;quot;).",
            "The ID of the user for whom to return results for.",
            "The screen name of the user for whom to return results for.",
            "Causes the list of connections to be broken into pages of no more than 5000 IDs at a time. The number of IDs returned is not guaranteed to be 5000 as suspended",
            "Many programming environments will not consume our Tweet ids due to their size. Provide this option to have ids returned as strings instead",
            "Specifies the number of IDs attempt retrieval of, up to a maximum of 5,000 per distinct request. The value of <tt>count</tt> is best thought of as a",
            "Returns a cursored collection of user objects for every user the specified user is following (otherwise known as their &amp;quot;friends&amp;quot;).",
            "The ID of the user for whom to return results for.",
            "The screen name of the user for whom to return results for.",
            "Causes the results to be broken into pages. If no cursor is provided, a value of <tt>-1</tt> will be assumed, which is the first page.<br /><br",
            "The number of users to return per page, up to a maximum of 200. Defaults to 20.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "The user object <tt>entities</tt> node will be disincluded when set to <tt>false</tt>.",
            "Returns settings (including current trend, geo and sleep time information) for the authenticating user.",
            "Updates the authenticating user's settings.",
            "The Yahoo! Where On Earth ID to use as the user's default trend location. Global information is available by using 1 as the WOEID. The woeid must be one of the",
            "When set to <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, will enable sleep time for the user. Sleep time is the time when push or",
            "The hour that sleep time should begin if it is enabled. The value for this parameter should be provided in <a href=http://en.wikipedia.org/wiki/ISO_8601",
            "The hour that sleep time should end if it is enabled. The value for this parameter should be provided in <a href=http://en.wikipedia.org/wiki/ISO_8601",
            "The timezone dates and times should be displayed in for the user. The timezone must be one of the <a target=_blank",
            "The language which Twitter should render in for this user. The language must be specified by the appropriate two letter ISO 639-1 representation. Currently",
            "Returns an HTTP 200 OK response code and a representation of the requesting user if authentication was successful; returns a 401 status code and an error message if",
            "The <tt>entities</tt> node will not be included when set to <tt>false</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Removes the uploaded profile banner for the authenticating user. Returns HTTP 200 upon success.",
            "Sets which device Twitter delivers updates to for the authenticating user. Sending none as the device parameter will disable SMS updates.",
            "Must be one of: <tt>sms</tt>, <tt>none</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt>, each tweet will include a node called entities,. This node",
            "Sets values that users are able to set under the &amp;quot;Account&amp;quot; tab of their settings page. Only the parameters specified will be updated.",
            "Full name associated with the profile. Maximum of 20 characters.",
            "URL associated with the profile. Will be prepended with http:// if not present. Maximum of 100 characters.",
            "The city or country describing where the user of the account is located. The contents are not normalized or geocoded in any way. Maximum of 30 characters.",
            "A description of the user owning the account. Maximum of 160 characters.",
            "The <tt>entities</tt> node will not be included when set to <tt>false</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Updates the authenticating user's profile background image. This method can also be used to enable or disable the profile background image. Although each",
            "The background image for the profile, base64-encoded. Must be a valid GIF, JPG, or PNG image of less than 800 kilobytes in size. Images with width larger than",
            "Whether or not to tile the background image. If set to <tt>true</tt>, <tt>t</tt> or <tt>1</tt> the background image will be",
            "The <tt>entities</tt> node will not be included when set to <tt>false</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Determines whether to display the profile background image or not. When set to <tt>true</tt>, <tt>t</tt> or <tt>1</tt> the",
            "Uploads a profile banner on behalf of the authenticating user. For best results, upload an",
            "The Base64-encoded or raw image data being uploaded as the user's new profile banner.",
            "The width of the preferred section of the image being uploaded in pixels. Use with <tt>height</tt>, <tt>offset_left</tt>, and <tt>offset_top</tt>",
            "The height of the preferred section of the image being uploaded in pixels. Use with <tt>width</tt>, <tt>offset_left</tt>, and <tt>offset_top</tt>",
            "The number of pixels by which to offset the uploaded image from the left. Use with <tt>height</tt>, <tt>width</tt>, and <tt>offset_top</tt>",
            "The number of pixels by which to offset the uploaded image from the top. Use with <tt>height</tt>, <tt>width</tt>, and <tt>offset_left</tt>",
            "Sets one or more hex values that control the color scheme of the authenticating user's profile page on twitter.com. Each parameter's value must be",
            "Profile background color.",
            "Profile link color.",
            "Profile sidebar's border color.",
            "Profile sidebar's background color.",
            "Profile text color.",
            "The <tt>entities</tt> node will not be included when set to <tt>false</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Updates the authenticating user's profile image. Note that this method expects raw multipart data, not a URL to an image. This method asynchronously",
            "The avatar image for the profile, base64-encoded. Must be a valid GIF, JPG, or PNG image of less than 700 kilobytes in size. Images with width larger than 500",
            "The <tt>entities</tt> node will not be included when set to <tt>false</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Returns the 20 most recent Tweets favorited by the authenticating or specified user.",
            "The ID of the user for whom to return results for.",
            "The screen name of the user for whom to return results for.",
            "Specifies the number of records to retrieve. Must be less than or equal to 200. Defaults to 20.",
            "Returns results with an ID greater than (that is, more recent than) the specified ID. There are limits to the number of Tweets which can be accessed through the",
            "Returns results with an ID less than (that is, older than) or equal to the specified ID.",
            "The <tt>entities</tt> node will be omitted when set to <tt>false</tt>.",
            "Favorites the status specified in the ID parameter as the authenticating user. Returns the favorite status when successful. This process invoked by this method is",
            "The numerical ID of the desired status.",
            "The <tt>entities</tt> node will be omitted when set to <tt>false</tt>.",
            "Un-favorites the status specified in the ID parameter as the authenticating user. Returns the un-favorited status in the requested format when successful. This",
            "The numerical ID of the desired status.",
            "The <tt>entities</tt> node will be omitted when set to <tt>false</tt>.",
            "Returns a collection of users that the specified user can &amp;quot;contribute&amp;quot; to.",
            "The ID of the user for whom to return results for. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "The screen name of the user for whom to return results for.",
            "The <tt>entities</tt> node will be disincluded when set to <tt>false</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Returns a collection of users who can contribute to the specified account.",
            "The ID of the user for whom to return results for.",
            "The screen name of the user for whom to return results for.",
            "The <tt>entities</tt> node will be disincluded when set to <tt>false</tt>.",
            "When set to either <tt>true</tt>, <tt>t</tt> or <tt>1</tt> statuses will not be included in the returned user objects.",
            "Returns fully-hydrated user objects for up to 100 users per request, as specified by comma-separated values passed to the user_id and/or screen_name parameters.",
            "A comma separated list of screen names, up to 100 are allowed in a single request. You are strongly encouraged to use a POST for larger (up to 100 screen names)",
            "A comma separated list of user IDs, up to 100 are allowed in a single request. You are strongly encouraged to use a POST for larger requests.",
            "The <tt>entities</tt> node that may appear within embedded statuses will be disincluded when set to <tt>false</tt>.",
            "Returns a map of the available size variations of the specified user's profile banner. If the user has not uploaded a profile banner, a HTTP 404 will be",
            "The ID of the user for whom to return results for. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "The screen name of the user for whom to return results for. Helpful for disambiguating when a valid screen name is also a user ID.",
            "Provides a simple, relevance-based search interface to public user accounts on Twitter. Try querying by topical interest, full name, company name, location, or other",
            "The search query to run against people search.",
            "Specifies the page of results to retrieve.",
            "The number of potential user results to retrieve per page. This value has a maximum of 20.",
            "The <tt>entities</tt> node will be disincluded from embedded tweet objects when set to <tt>false</tt>.",
            "Returns a variety of information about the user specified by the required user_id or screen_name parameter. The author's most recent Tweet will be returned",
            "The ID of the user for whom to return results for. Either an id or screen_name is required for this method.",
            "The screen name of the user for whom to return results for. Either a id or screen_name is required for this method.",
            "The <tt>entities</tt> node will be disincluded when set to <tt>false</tt>.",
            "Access to Twitter's suggested user list. This returns the list of suggested user categories. The category can be used in GET users/suggestions/:slug to get",
            "Restricts the suggested categories to the requested language. The language must be specified by the appropriate two letter ISO 639-1 representation. Currently",
            "Access the users in a given category of the Twitter suggested user list. It is recommended that applications cache this data for no more than one hour.",
            "The short name of list or a category",
            "Restricts the suggested categories to the requested language. The language must be specified by the appropriate two letter ISO 639-1 representation. Currently",
            "Access the users in a given category of the Twitter suggested user list and return their most recent status if they are not a protected user.",
            "The short name of list or a category",
            "Report the specified user as a spam account to Twitter. Additionally performs the equivalent of POST blocks/create on behalf of the authenticated user.",
            "The ID or screen_name of the user you want to report as a spammer. Helpful for disambiguating when a valid screen name is also a user ID.",
            "The ID of the user you want to report as a spammer. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "Returns the current rate limits for methods belonging to the specified resource families.",
            "A comma-separated list of resource families you want to know the current rate limit disposition for. For best performance, only specify the resource families",
            "Returns the 20 most recent direct messages sent by the authenticating user. Includes detailed information about the sender and recipient user. You can request up to",
            "Returns results with an ID greater than (that is, more recent than) the specified ID. There are limits to the number of Tweets which can be accessed through the",
            "Returns results with an ID less than (that is, older than) or equal to the specified ID.",
            "Specifies the number of records to retrieve. Must be less than or equal to 200.",
            "Specifies the page of results to retrieve.",
            "The <tt>entities</tt> node will not be included when set to <tt>false</tt>.",
            "Returns a single direct message, specified by an id parameter. Like the /1.1/direct_messages.format request, this method will include the user objects of the sender",
            "The ID of the direct message.",
            "Destroys the direct message specified in the required ID parameter. The authenticating user must be the recipient of the specified direct message. Important: This",
            "The ID of the direct message to delete.",
            "The <tt>entities</tt> node will not be included when set to <tt>false</tt>.",
            "Sends a new direct message to the specified user from the authenticating user. Requires both the user and text parameters and must be a POST. Returns the sent",
            "The ID of the user who should receive the direct message. Helpful for disambiguating when a valid user ID is also a valid screen name.",
            "The screen name of the user who should receive the direct message. Helpful for disambiguating when a valid screen name is also a user ID.",
            "The text of your direct message. Be sure to URL encode as necessary, and keep the message under 140 characters.",
    };


}
