//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.27 at 12:09:46 AM EET 
//


package com.tomitribe.wadl.api;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tomitribe.wadl.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ApiVersion_QNAME = new QName("http://www.tomitribe.com/schemas/2014/02/wadl/extension/other", "api-version");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tomitribe.wadl.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link ResponseObject }
     * 
     */
    public ResponseObject createResponseObject() {
        return new ResponseObject();
    }

    /**
     * Create an instance of {@link ApiVersions }
     *
     */
    public ApiVersions createApiVersions() {
        return new ApiVersions();
    }

    /**
     * Create an instance of {@link Categories }
     *
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link Response }
     *
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Tags }
     *
     */
    public Tags createTags() {
        return new Tags();
    }

    /**
     * Create an instance of {@link ResourceType }
     *
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link Doc }
     *
     */
    public Doc createDoc() {
        return new Doc();
    }

    /**
     * Create an instance of {@link Representation }
     *
     */
    public Representation createRepresentation() {
        return new Representation();
    }

    /**
     * Create an instance of {@link Rates }
     *
     */
    public Rates createRates() {
        return new Rates();
    }

    /**
     * Create an instance of {@link Option }
     *
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link Grammars }
     *
     */
    public Grammars createGrammars() {
        return new Grammars();
    }

    /**
     * Create an instance of {@link SeeAlso }
     *
     */
    public SeeAlso createSeeAlso() {
        return new SeeAlso();
    }

    /**
     * Create an instance of {@link Rate }
     *
     */
    public Rate createRate() {
        return new Rate();
    }

    /**
     * Create an instance of {@link Request }
     *
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link RolesAllowed }
     *
     */
    public RolesAllowed createRolesAllowed() {
        return new RolesAllowed();
    }

    /**
     * Create an instance of {@link Param }
     *
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Method }
     *
     */
    public Method createMethod() {
        return new Method();
    }

    /**
     * Create an instance of {@link Include }
     *
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link Link }
     *
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link RequestObject }
     *
     */
    public RequestObject createRequestObject() {
        return new RequestObject();
    }

    /**
     * Create an instance of {@link Resources }
     *
     */
    public Resources createResources() {
        return new Resources();
    }

    /**
     * Create an instance of {@link See }
     *
     */
    public See createSee() {
        return new See();
    }

    /**
     * Create an instance of {@link Application }
     *
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tomitribe.com/schemas/2014/02/wadl/extension/other", name = "api-version")
    public JAXBElement<String> createApiVersion(String value) {
        return new JAXBElement<String>(_ApiVersion_QNAME, String.class, null, value);
    }

}
